### ISSUE TITLE
[V4.0] No error for missing element or null element passed

### ISSUE THREAD

**Issue by ili101** [adamdriscoll/selenium-powershell#135] opened 2020-09-21 16:26 UTC
Hi
I started working with the module. Took me some time to realize that there is already a compiled version in the Output folder 😅.
Usually if something is wrong I want to know about it immediately. I used to use `FindElement()` so if the element is not found I get an error immediately but here as you use `FindElements()` I don't get any error and the code continues but I see this is the same beaver as in V3 so it's probably buy design.
The bigger problem is that in V3 if you pipe this missing element (null) to an action you get an error but in V4 it continues so you can have many lines of actions that fail and the script will keep running.
``` powershell
Get-SeElement -By Id -Value 'User' | Send-SeKeys -Keys 'Key' # This should fail as in V3.

function Verb-Noun {
    [CmdletBinding()]
    param ( )
}
Verb-Noun | Send-SeKeys -Keys 'Key' # This also passes without an error in V4.
```

**Comment by itfranck** [comment] 2020-09-22 00:16
@ili101 Good catch ! 
I'll look at this shortly. 

Some other cmdlets will suffer the same fate. 
I'll make sure to take care of them too. 



--- 
Not related to this issue but you mentionned the Output folder.
You should not need it for anything mostly.
You can load the debug version by importing the psd1 at the root of the module. 

The output folder and its content is deleted / recreated when the Invoke-Build statement is called  (see Debug.ps1 for an example) 

(Maybe this was all clear already, I am just mentioning it in case you develop in the output location directly) 
(Additional note: VsCode have the annoying tendency of opening the output of Selenium.psm1 regardless of which version is loaded when using CTRL + click on a function defnition even though the actual code being used is within the )

**Comment by ili101** [comment] 2020-09-22 08:19
Thank you for the tips.
Yes I used the root psd1 in the beginning but then I had the problems mention here https://github.com/adamdriscoll/selenium-powershell/issues/77 as the classes where not in the psm1 file. In this case PowerShell loads them to the correct scope where you import the module and not the global one so you can have some problems.

**Comment by itfranck** [comment] 2020-09-30 02:58
@ili101 
I added  a `[ValidateNotNull()]` condition so that the following will be caught properly

```
#Now throw an error 
$null | invoke-SeKeys -Keys 'Key'
```

That being said, at the core of the issue you mentioned, this is a Powershell normal behavior.
No  downstream cmdlet in the pipeline will throw error when subjected to the initial premise. 

```
Verb-Noun | Stop-Process
Verb-Noun | ForEach-Object {Write-Host 'Hello'}
Verb-Noun | Import-Module
Verb-Noun | Invoke-Command {Write-Host 's'}
```
Note that in all these cases, using an empty array `@()` will also never throw an error.

```
@()  | Stop-Process
```


Even more examples
```

# Downstream cmdlet do not care * 
Verb-Noun | Stop-Process
@()       | Stop-Process

# Downstream cmdlet care very much
$null     | Stop-Process
1         | Stop-Process
@($null)  | Stop-Process

```

**Reference:**
https://community.spiceworks.com/topic/740612-empty-pipeline-parameter-binding

**Comment by itfranck** [comment] 2020-09-30 03:14
Technically the following workaround could be implemented. 


```
Function Process-Pipeline {
    [CmdletBinding()] 
    Param(
        [Parameter(ValueFromPipeline = $true)]
        $InputObject
    ) 
    Begin {
        Write-Verbose 'Begin'
        $IsValid = $false
    }
    Process {
        $IsValid = $true
        Write-Verbose "Process $_"
    }
    End {
        if ($PSCmdlet.MyInvocation.ExpectingInput -and -Not $IsValid) {
            throw 'NO NO NO NO :['
        }
        Write-Verbose "End"
    }
}
```

I guess I could be implementing it for Get-SeElement to make sure any downstream cmdlet that do not accept $null input fails.

**Comment by itfranck** [comment] 2020-09-30 03:40
Ah, it looks like this is a Powershell Pandora box in some way. 

The process block of the downstream cmdlet is never entered but that's not tied to this module, it is part of the core design.
This also happens with empty arrays `@()`. 

For instance, consider the following
```

# Downstream cmdlet do not care * 
Verb-Noun | Stop-Process
@()             | Stop-Process

# Downstream cmdlet care very much
$null        | Stop-Process
1              | Stop-Process
@($null)  | Stop-Process

```

### **So, what can be done ?**

I found two ways to address the situation. 
The first one is to initialize a variable in the **Begin** block, assign it in the process block (it will get assigned potentially many times) and ensure that if the cmdlet was expecting input, then that the variable should be initialized or throw an error.

Something like this.
```

Function Process-Pipeline {
    [CmdletBinding()] 
    Param(
        [Parameter(ValueFromPipeline = $true)]
        $InputObject
    ) 
    Begin {
        Write-Verbose 'Begin'
        $IsValid = $false
    }
    Process {
        $IsValid = $true
        Write-Verbose "Process $_"
    }
    End {
        if ($PSCmdlet.MyInvocation.ExpectingInput -and -Not $IsValid) {
            throw 'NO NO NO NO :['
        }
        Write-Verbose "End"
    }
}
```

Then again, I don't really like the solution as this would have to be done everywhere and even Powershell cmdlet (all of them) do not explicitely handle that. 


### The solution

The solution is to get the upstream cmdlet to return an explicit `$null` 
If we get back to the context of this module, Get-SeElement (which will likely be the upstream cmdlet) return `$output`

```
return $Output
```

If no element were found, `$Output` will be `$null` and the downstream cmdlet (in this case `Invoke-SeKeys`, will never get it's `$Element` variable assigned (and [ValidateNotNull()] is not effective against empty arrays or "implicit" `$null` coming from the upstream source. 

That being said, returning an explicit `$null` from `Get-SeElement` will be caught in `[ValidateNotNull()]` from the downstream cmdlet and generate the error as expected. 

```
#New return from Get-SeElement with explicit $null being returned.
if ($null -eq $Output) {return $null} else {return $Output}
```

Thus, this will be the solution I will apply. 

This won't prevent  the following from still failing
```
Verb-Noun | Invoke-SeKeys -Keys 'Hello World'
@()             |  Invoke-SeKeys -Keys 'Hello World'
```

but will now generate an error on  real use cases

```
#Assumption is Get-SeElement return no elements
Get-SeElement -By Name -Value 'FakeName' | Invoke-SeKeys -Keys 'Hello World'
```

**Comment by vexx32** [comment] 2020-09-30 03:48
@itfranck can we handle this with parameter validation ? Handling this sort of thing manually is usually a good bit more complicated.

A `[ValidateNotNull()]` for that parameter should be sufficient, I'd think.

**Comment by itfranck** [comment] 2020-09-30 04:17
@vexx32 

From what I gathered, it is not sufficient.

Here's a simplified reproducible example. 


### Functions definitions
```

Function Verb-Noun() {
    [CmdletBinding()]
    Param([Switch]$ExplicitNull) 
    if ($ExplicitNull) { return $null }
}

Function Process-Pipeline() {
    [CmdletBinding()]
    Param(
        [Parameter(ValueFromPipeline = $true)]
        [ValidateNotNull()]
        $InputObject
    ) 
    Begin {
        Write-Verbose 'Entered Begin block' 
    }
    Process {
        Write-Verbose 'Entered Process block' 
    }
    End {
            Write-Verbose 'Entered End block' 
    }
       
}
```

### Actual sample to run
```

#Equivalent to Get-SeElement when it does not find anything
Write-Host 'Upstream cmdlet do not return anything'  -ForegroundColor Cyan
Write-Host 'Get-SeElement react this way when it find 0 element'  -ForegroundColor Green
Verb-Noun | Process-Pipeline -Verbose

Write-Host '---'
Write-Host 'Upstream cmdlet return $null'  -ForegroundColor Cyan
Verb-Noun -ExplicitNull  | Process-Pipeline -Verbose
```

I'll save you the trouble of running it. 


![image](https://user-images.githubusercontent.com/1980296/94641883-80014a80-02b0-11eb-8b22-81301198e85e.png)


The first example is calling `Verb-Noun` that have no return.
The `[ValidateNotNull()]` have no effect on the `$InputObject` as it is provided from the pipeline 
(If you were to provide it through the parameter, then `[ValidateNotNull()]` would catch it correctly.) 

The second example is the same, except that `Verb-Noun` cmdlet return `$null`
The execution never proceed into the process block as the  `[ValidateNotNull()]` is evaluated and an error is thrown since the condition is not met. 


This is a behavior that seems ubiquitous. 
If you have a better solution though, let me know. 
I am always looking to learn more. 
It seems to me I have hit some edge-case with this one based on the comments from the previous post with and the referenced discussion below. 


Some more discussion I found while looking for a proper solution 
https://community.spiceworks.com/topic/740612-empty-pipeline-parameter-binding

**Comment by itfranck** [comment] 2020-09-30 04:41
Interesting side-note. 

In the context of this module, `Get-SeElement`, when it does not find anything, return `$null`
```
 $Output = $Element.FindElements($ByCondition) | DisplayedFilter -All:$ShowAll
#...
return $Output
```

But an actual `$null` value should fail when the pipeline is processed (as per example #2 of my previous message.
That being said, it does not, which force me to do this : 

```
if ($null -eq $Output) { return $null } else { return $Output }
```
to ensure that any downstream cmdlet called after `Get-SeElement` fail if the upstream do not produce a value.

I think the key is what kind of `$null` value is generated. 
Implicit `$null` do not get parameter validated against `[ValidateNotNull()]` attribute in the PROCESS scriptblock.
Explicit `$null` do get evaluated and catched. 

Here's a simple example using the same `Process-Pipeleine` function as before, but with a slightly modified `Verb-Noun` definition.

```
Function Verb-Noun() {
    [CmdletBinding()]
    Param([Switch]$ExplicitNull, [Switch]$ImplicitNull) 
    if ($ExplicitNull) { return $null }
    if ($ImplicitNull) { return [System.Management.Automation.Internal.AutomationNull]::Value }
}
Write-Host "Implicit `$null is `$null: $((Verb-Noun -ImplicitNull) -eq $null)" -ForegroundColor Cyan
Verb-Noun -ImplicitNull | Process-Pipeline -Verbose

Write-Host "Explicit `$null is `$null: $((Verb-Noun -ImplicitNull) -eq $null)" -ForegroundColor Cyan
Verb-Noun -ExplicitNull | Process-Pipeline -Verbose
```

![image](https://user-images.githubusercontent.com/1980296/94643491-f0aa6600-02b4-11eb-8c76-230744a619f0.png)

My thought is that the `$null` returned by the .net call made by `Get-SeElement` is wrapped internally into a `$null` value of 
 type `[System.Management.Automation.Internal.AutomationNull]::Value` while the explicit `$null` keyword is something different (even if both evaluate to `$null`) 

Based on that example, that seem to hold the route and explain why the downstream cmdlet behave differently in both case and why I had ultimately to explicitly return `$null` in `Get-SeElement` instead of allowing the inferred `$null` to go downstream.

**Comment by vexx32** [comment] 2020-09-30 11:15
In general, returning `$null` in any fashion from a PS cmdlet is probably not a great idea. If the cmdlet returns nothing (aka `AutomationNull.Value`) then a downstream pipeline cmdlet doesn't have its `process` block invoked in the first place. That's _generally_ the better option, but I can see that it's probably nicer here to indicate to the user that whatever click/etc operation they were trying to do failed...

I'm not sure if returning `$null` is the best way to go though, it might end up passing the buck to the user to handle the null output when it might just be better to emit the error directly from `Get-SeElement`. That's not an easy thing to be sure you want an error there, though; most `Get` cmdlets will generally just return null if nothing is found.

One option might be to use the `process` block of `Invoke-SeClick` (and anything similar that needs the behaviour to work like this) to just collect a list of elements, and use the `end` block to go through and click all of them in turn, or something. That way you can check there for an empty collection and throw if there's no input elements to click on. It is still a bit of a workaround though 🤔

**Comment by itfranck** [comment] 2020-09-30 15:27
I can't attest for all but some base `Get` cmdlet definitely return an error if used with a parameter set. 
For instance
```
Get-Job -Name 'hair'
Get-process -Name 'hair'
```

I think `Get-SeElement` should behave in the same manner and throw an error if there's no element. 
Even without error, You'd already need anyway to have logic around the fact you did or did not have results so it would make perfect sense.

That way
- We avoid explicit `$null` workaround (that have the side effect to trigger process block in downstream cmdlet)
- We avoid `End` block processing workaround (which work well but is still a bit meh) 
- We get informed whatever the situation that `Get-SeElement` with specified parameter did not produce a result (That has an effect on downstream code too, not just pipeline) 

I was not too convinced initially but I was fleshing out my answer again and again, I now strongly believe that would be the best course of action.

**Comment by vexx32** [comment] 2020-09-30 15:35
Hm, true. I think it more depends on whether the result is expected to include more than one element (or could). For example, `Get-Item noFile` will error, but `Get-Item no*file*` will not (wildcards -- expected to find potentially more than one item, or none).

With the way Get-SeElement behaves it's... complicated to adopt quite the same model, so perhaps it makes the most sense to just error... I guess finding elements by tag name or class, you would somewhat commonly expect to potentially get multiple items back, so it might make less sense to error there, but for `id` you generally expect just one item...

But then again, consistent behaviour is generally easier for folks to deal with, so perhaps just erroring in all cases if nothing is found is the best way to go.

**Comment by itfranck** [comment] 2020-09-30 16:15
Indeed.

Consistent behavior is the key. 

I do think that the error throw would be a good solution to this issue.

I see no erroring wildcard support as another potential enhancement to this.
Provided no erroring wildcard support is implemented across the board to not produce error and documented, then the behavior would still be consistent and even closer to the "base" Powershell cmdlets which seems like a good reference when looking for consistent behavior, globally speaking. 


---

As a parallel thought, it might be interesting to have a `-Unique`  (`-Single` ? ; `-First` ?) switch parameter to throw an error if more than 1 element is returned.

That would be practical when you want to select a specific button to have the embedded conditional validation.

**Comment by vexx32** [comment] 2020-09-30 16:22
Not sure on `FindElement()` vs `FindElements()`; personally I think:

- when using a search by element **id**, use `FindElement()`
- otherwise, use `FindElements()` unless an additional switch is passed (e.g., `-First`)

I'm not especially a fan of _requiring_ an additional switch to get more than one item personally, I feel that's going to be more annoying than useful.

---

Other than that, the other suggestions sound good to me. I will caution that in most cases I'd probably recommend using non-terminating errors, but everything else sounds good. 🙂

**Comment by ili101** [comment] 2020-09-30 16:36
I was also thinking on `-First` but then I realized that the user code will probably be 100 commands that are all `Get-SeElement -First ...`, so it will be annoying.
Regarding extra optional switches you can borrow the names from Linq like [Single](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.single?view=netcore-3.1), [First](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.first?view=netcore-3.1), [Last](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.last?view=netcore-3.1) and the other ones from the document

**Comment by itfranck** [comment] 2020-09-30 17:11
@ili101 

I thought that initially too that it would be annoying but then, consider the following

- `Get-SeElement` where multiple elements are expected is still a relatively common scenario, so you'll still end up with a lot of `-Multiple` everywhere (even if less) 
- `Get-SeElement -Single` is really just optional... You don't use it and there's only 1 corresponding element in the page, that is what you'll get. The only difference is whether or not you want an error if there's more than 1 element. 

`-Multiple` switch would be required anytime you want multiple elements. `-Single` switch is very optional and only determine whether or not you get an error (Not using it if you're confident there's only one element and don't want / need the extra validation. 

- A lot of time, particularly when writing / debugging, I do want to have multiple elements  as I am inspecting the page. 

As for `-First`, I was thinking of Ienumerable / First (vs FirstorDefault) but I like much more `-Single` as `-First` might imply that if multiple elements are to be returned, you want the first one, rather than a conditional validation on the 1 element expected. 

Anyway, I'll open a separate item for that specifically as we slided away from this specific issue problematic (which will be addressed by the Throw on empty)

**Comment by itfranck** [comment] 2020-09-30 17:55
Done. I'll address the "Only one element when using By ID" through #144

**Closed** 2020-09-30 18:31 UTC
Labels: bug
